version: 2.1

jobs:
  build:
    docker:
      - image: hexpm/elixir:1.11.4-erlang-23.3.1-alpine-3.13.3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install hex and rebar
          command: |
            mix local.hex --force
            mix local.rebar --force
      - restore_cache:
          keys:
            - v1-mix-cache-{{ checksum "mix.lock" }}
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix format --check-formatted
      - run: mix deps.unlock --check-unused
      - run: mix dialyzer
      - run: mix test
      - run: mix docs
      - run: mix hex.build
      - save_cache:
          key: v1-mix-cache-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
